### ISSUE TITLE
Factory example does not work

### ISSUE THREAD

**Issue by Alexrs95** [rinde/RinSim#49]
When trying to run `FactoryExample.java` the following error appears:

```
Exception in thread "main" java.lang.IllegalArgumentException: A MovingRoadUser can not be added on an already occupied position (1140.0,90.0).
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:146)
	at com.github.rinde.rinsim.core.model.road.CollisionGraphRoadModelImpl.addObjectAt(CollisionGraphRoadModelImpl.java:152)
	at com.github.rinde.rinsim.core.model.pdp.PDPObjectImpl.initRoadUser(PDPObjectImpl.java:77)
	at com.github.rinde.rinsim.core.model.road.AbstractRoadModel.doRegister(AbstractRoadModel.java:298)
	at com.github.rinde.rinsim.core.model.road.GenericRoadModel.register(GenericRoadModel.java:106)
	at com.github.rinde.rinsim.core.model.road.GenericRoadModel.register(GenericRoadModel.java:34)
	at com.github.rinde.rinsim.core.model.ModelManager.doRegister(ModelManager.java:95)
	at com.github.rinde.rinsim.core.model.ModelManager.register(ModelManager.java:115)
	at com.github.rinde.rinsim.core.Simulator.register(Simulator.java:110)
	at com.github.rinde.rinsim.examples.demo.factory.FactoryExample.run(FactoryExample.java:167)
	at com.github.rinde.rinsim.examples.demo.factory.FactoryExample.main(FactoryExample.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

The problem is at [this line](https://github.com/rinde/RinSim/blob/master/example/src/main/java/com/github/rinde/rinsim/examples/demo/factory/FactoryExample.java#L167).

If we change it by 

```JAVA
    for (int i = 0; i < NUM_VEHICLES; i++) {
      final List<Point> l = points.get(rng.nextInt(points.size()));
      final Point p = l.get(i);
      simulator.register(new AGV(p));
    }
```
it seems to work, but I don't know if the purpose of this demo is to initialise the `AGVs` in certain positions. (Don't think so, as they are initialised randomly).

Let me know if I have to create a PR to fix this issue.

**Comment by rinde** [comment]
Hi @Alexrs95, thanks for your message!

I can't seem to reproduce your exception in version 4.5.0-SNAPSHOT (in develop branch) or in version 4.4.1 (latest release). Which version are you on?

**Comment by Alexrs95** [comment]
I have tried in both `4.5.0-SNAPSHOT` and `4.4.1` in Mac OS 10.11 with Java 1.8. I'll try to reproduce the issue in another computer and I'll keep you updated.

**Comment by Alexrs95** [comment]
Executing the same example in Ubuntu seems to work. I don't know what can be the cause of the problem. Could it be related somehow to the random number generator and the OS in which it is executed?

**Comment by rinde** [comment]
The random seed is hardcoded in the example, so it should behave exactly the same on every platform. I've tested it on Mac OS 10.12.3 and see no problem here. Are you still seeing this issue? Have you restarted your computer in the meantime?

**Comment by Alexrs95** [comment]
After updating to macOS 10.12.4 it works, so I close the issue. Weird bug, though.
